#ifndef _ANT_CONFIG_H_
#define _ANT_CONFIG_H_


#define ROBOT_TYPE_BASE         AGENT_TYPE_BEHAVIOUR_TYPE_0
#define ROBOT_TYPE_FOOD         AGENT_TYPE_BEHAVIOUR_TYPE_1

#define ROBOT_TYPE_ANT          AGENT_TYPE_BEHAVIOUR_TYPE_2
#define ROBOT_TYPE_PHEROMONE    AGENT_TYPE_BEHAVIOUR_TYPE_3


#endif
