#ifndef _CONFIGURATION_H_
#define _CONFIGURATION_H_

#include "common.h"

#define VISUALISATION_3D_MODE			1

#define VISUALISATION_SCREEN_WIDTH		(u32)1280
#define VISUALISATION_SCREEN_HEIGHT		(u32)720

// #define VISUALISATION_FULL_SCREEN		(u32)1

#define VISUALISATION_ROBOT_SIZE 		(float)(0.5)	//robot size
#define VISUALISATION_SIZE_RATIO		(float)(1.0)
// #define VISUALISATION_SIZE_RATIO		(float)0.01

#endif
